import { v4 as uuidv4 } from 'uuid'
import type { Song } from '../types'

const rawSongs: Omit<Song, 'id'>[] = [
  {
    title: 'The Awakening',
    streams_28d: 22407,
    listeners: 10898,
    saves: 388,
    programmed_pct: 66,
    active_pct: 30,
    daily_budget_sek: 150,
  },
  {
    title: 'Antihero',
    streams_28d: 16012,
    listeners: 7510,
    saves: 244,
    programmed_pct: 42,
    active_pct: 55,
    daily_budget_sek: 150,
  },
  {
    title: 'One More Day',
    streams_28d: 12503,
    listeners: 7136,
    saves: 154,
    programmed_pct: null,
    active_pct: null,
    daily_budget_sek: 50,
  },
  {
    title: 'Predators',
    streams_28d: 4911,
    listeners: 2909,
    saves: 52,
    programmed_pct: null,
    active_pct: null,
    daily_budget_sek: 0,
  },
  {
    title: 'Pushing Through',
    streams_28d: 4255,
    listeners: 2039,
    saves: 93,
    programmed_pct: 61,
    active_pct: 36,
    daily_budget_sek: 0,
  },
  {
    title: 'One in a Million',
    streams_28d: 3331,
    listeners: 1577,
    saves: 137,
    programmed_pct: 48,
    active_pct: 48,
    daily_budget_sek: 30,
  },
  {
    title: 'The Wave',
    streams_28d: 2362,
    listeners: 1628,
    saves: 37,
    programmed_pct: 79,
    active_pct: 19,
    daily_budget_sek: 0,
    trend_pct: -19.8,
  },
  {
    title: 'Hollow',
    streams_28d: 2008,
    listeners: 1225,
    saves: 57,
    programmed_pct: 54,
    active_pct: 44,
    daily_budget_sek: 0,
  },
  {
    title: 'Roots',
    streams_28d: 2009,
    listeners: 1145,
    saves: 67,
    programmed_pct: 57,
    active_pct: 42,
    daily_budget_sek: 5,
    trend_pct: 28.5,
  },
  {
    title: 'Dead End Loser',
    streams_28d: 1599,
    listeners: 867,
    saves: 42,
    programmed_pct: 16,
    active_pct: 82,
    daily_budget_sek: 20,
    trend_pct: 21.1,
  },
  {
    title: 'Alone Against the World',
    streams_28d: 1562,
    listeners: 1014,
    saves: 28,
    programmed_pct: 56,
    active_pct: 40,
    daily_budget_sek: 0,
  },
  {
    title: 'When I Close My Eyes',
    streams_28d: 1537,
    listeners: 930,
    saves: 27,
    programmed_pct: 40,
    active_pct: 58,
    daily_budget_sek: 0,
    trend_pct: 24.7,
  },
  {
    title: 'Dust',
    streams_28d: 1321,
    listeners: 790,
    saves: 43,
    programmed_pct: 68,
    active_pct: 30,
    daily_budget_sek: 0,
    trend_pct: 2.3,
  },
  {
    title: 'Resonate',
    streams_28d: 989,
    listeners: 456,
    saves: 49,
    programmed_pct: 40,
    active_pct: 55,
    daily_budget_sek: 20,
    trend_pct: 34.3,
  },
]

export const DEFAULT_SONGS: Song[] = rawSongs.map((s) => ({
  ...s,
  id: uuidv4(),
}))
